### PR TITLE
Implemented a fast FNV hash to map int labels to float [0,1]

### PR DESCRIPTION
**Pull request by OKaluza**
# Description
Fix the mapping of labels to [0,1] floats with a hash to uint32 then divide by uint32max to floats.
Tried crc32 and other hash functions, the one used is nice because it's simple enough to implement with numpy vector operations and seems to be fast enough in my testing.

## Type of change
- [x] Bug-fix (non-breaking change which fixes an issue)

# References
https://github.com/napari/napari/pull/713

# How has this been tested?
I have not run the ci tests. I benchmarked the speed of the hash operation, it runs in < 0.2 sec on the test machine. Compared with zlib.crc32 in loop: ~2 seconds. 

## Final checklist:
- [x] My PR is the minimum possible work for the desired functionality
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by jni** [comment]
@OKaluza Awesome! Thank you for wrapping this up last night! 🎉 I'll play around with it a bit later today and then probably merge!

**Comment by jni** [comment]
@OKaluza what testing have you done on this? Currently if I run `%timeit` on this function for a (2048, 2048) uint32 image, I get 560ms on my Macbook! 😬 

Medium term, do you think it would be possible to implement this is in a shader? I think your rationale for using this function is very good.

**Comment by OKaluza** [comment]
> @OKaluza what testing have you done on this? Currently if I run `%timeit` on this function for a (2048, 2048) uint32 image, I get 560ms on my Macbook! grimacing
> 
I was just using the time module, I had < 200 ms on my laptop.
But yeah, you're running this hash on every pixel, it's not going to be fast, I'm pretty sure we're not going to get much better than this on the cpu, but would improve with a parallel implementation.
> Medium term, do you think it would be possible to implement this is in a shader? I think your rationale for using this function is very good.

Yes, as discussed on friday - I not only think it's possible but the best way by far and probably would take less effort than this attempt at doing it on the cpu did. When already using the gpu to render it makes way more sense to move this calculation there too, anyway I learnt a bit about the napari source and found a neat hash function that might work in a gpu implementation too.

**Comment by jni** [comment]
Ah I forgot to send you the link about where vispy always copies volumes to float32. See this PR to get oriented:

https://github.com/vispy/vispy/pull/1728/files

The idea would be to optionally remove the copy (which you can do if you don't automatically modify the array in-place) and allow integer volumes/images, and then do the hashing on the shader. I presume there is a similar pathway in the Image visual.

**Comment by wangyi-fudan** [comment]
just mention wyhash, the fastest high quality conventional hash function:
https://github.com/wangyi-fudan/wyhash

**Pull request closed without merging**
